Unit tests for MusicAlbum and Genre classes
migo1/catalog-of-my-things pull request #46
Opened 2023-09-11 19:11 UTC by abdozayan12

Add unit tests for all implemented methods.

2023-09-11 22:22 UTC, marvin-nyalik requested changes
Hi @abdozayan12, you made great progress with the tests.

In this unit testing branch, some tests are passing while others are not. Please review the code and make appropriate changes for all tests to be positive. Cheers 🎉.

2023-09-11 22:22 UTC, marvin-nyalik commented on src/spec/genre_spec.rb
> +end
Hi @abdozayan12, Great job with the unit tests. I however noticed that the above 2 tests are failing. Kindly make the necessary changes to allow all tests to pass.

2023-09-11 22:22 UTC, marvin-nyalik commented on src/spec/music_album_spec.rb
> +
For some reason, all the tests for the MusicAlbum are failing. Kindly inspect the code and ensure the results are positive.
<img width="616" alt="music_test" src="https://github.com/migo1/catalog-of-my-things/assets/81169099/f1647e5a-a9bc-47d6-b50d-bfbcce19e8a7">

2023-09-13 06:26 UTC, migo1 approved these changes
Hi @abdozayan12  

Good job!

## Highlights

✅ Linters are passing
✅ Good commit history
✅ Tests are passing

### Approved 👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-09-13 06:28 UTC, merged